# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.9'

services:

  app:
    image: emmanuel_blog
    container_name: Blog
    build:
      context: .
      dockerfile: src/Blog.Api/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Blog.Api.pfx
    volumes:
      - ~/.aspnet/https:/https:ro